In [1]:
import pandas as pd
import numpy as np

pd.set_option(
    "display.max_columns",
    20
)

In [4]:
prices = pd.read_csv(
    "../nifty500_statergy/data/nifty500_close_clean.csv",
    index_col=0,
    parse_dates=True
)

In [5]:
print(
    "Price Shape:",
    prices.shape
)

print(
    "Date Range:",
    prices.index.min(),
    "to",
    prices.index.max()
)

print(
    "Number of Stocks:",
    len(prices.columns)
)

Price Shape: (2716, 332)
Date Range: 2015-01-01 00:00:00 to 2025-12-31 00:00:00
Number of Stocks: 332

In [6]:
prices.head()

,3MINDIA.NS,ABB.NS,ACC.NS,AIAENG.NS,APLAPOLLO.NS,AARTIIND.NS,ABBOTINDIA.NS,ACE.NS,ADANIENSOL.NS,ADANIENT.NS,...,WIPRO.NS,WOCKPHARMA.NS,YESBANK.NS,ZFCVINDIA.NS,ZEEL.NS,ZENTEC.NS,ZENSARTECH.NS,ZYDUSLIFE.NS,ZYDUSWELL.NS,ECLERX.NS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-01,6042.789062,1126.536133,1236.871338,1001.922424,31.517538,59.092567,3356.491455,38.261906,NaN,70.729744,...,91.154800,928.719971,147.012482,742.242615,346.171448,NaN,102.716225,292.863586,154.284592,312.330841
2015-01-02,6032.430664,1114.850952,1256.567139,1019.231934,31.723621,59.620903,3438.530518,38.643093,NaN,71.076172,...,91.963379,940.678467,150.751801,766.081055,349.150146,NaN,103.885956,295.706818,152.250000,320.748352
2015-01-05,6024.022949,1115.110474,1263.396973,1023.329163,30.843063,58.713551,3542.943848,38.786045,NaN,72.252594,...,92.128410,945.225464,151.075287,771.907043,348.279510,NaN,102.122894,308.742249,152.972534,320.796783
2015-01-06,5883.372070,1104.983765,1219.246460,984.705139,30.730652,58.139282,3599.254639,38.357204,NaN,71.704071,...,89.974937,890.798157,146.841232,735.192200,337.189545,NaN,100.232658,301.620453,148.399551,307.776917
2015-01-07,5847.976562,1089.056885,1205.058350,969.145020,30.716604,56.933308,3635.176758,36.975388,NaN,71.068947,...,89.290146,907.258240,144.119995,740.960815,334.394104,NaN,100.029236,299.567535,149.388306,308.055511

In [7]:
prices.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2716 entries, 2015-01-01 to 2025-12-31
Columns: 332 entries, 3MINDIA.NS to ECLERX.NS
dtypes: float64(332)
memory usage: 6.9 MB

In [8]:
missing = (
    prices.isna()
    .mean()
    .sort_values(
        ascending=False
    )
)

missing.head(20)

BSE.NS           0.189617
LAURUSLABS.NS    0.177467
VBL.NS           0.167158
PNBHOUSING.NS    0.166789
ENDURANCE.NS     0.162371
ICICIPRULI.NS    0.157953
LTTS.NS          0.156480
RBLBANK.NS       0.150957
LTM.NS           0.140648
MGL.NS           0.135862
BLS.NS           0.131443
CROMPTON.NS      0.122975
NH.NS            0.091679
LALPATHLAB.NS    0.088365
ALKEM.NS         0.088365
INDIGO.NS        0.078056
IDFCFIRSTB.NS    0.077320
SYNGENE.NS       0.055596
ADANIENSOL.NS    0.053019
INOXWIND.NS      0.023932
dtype: float64

In [9]:
print("Shape:", prices.shape)

print("\nDate Range:")
print(prices.index.min())
print(prices.index.max())

print("\nStocks:")
print(len(prices.columns))

Shape: (2716, 332)

Date Range:
2015-01-01 00:00:00
2025-12-31 00:00:00

Stocks:
332

In [10]:
prices.iloc[:5, :5]

             3MINDIA.NS       ABB.NS       ACC.NS    AIAENG.NS  APLAPOLLO.NS
Date
2015-01-01  6042.789062  1126.536133  1236.871338  1001.922424     31.517538
2015-01-02  6032.430664  1114.850952  1256.567139  1019.231934     31.723621
2015-01-05  6024.022949  1115.110474  1263.396973  1023.329163     30.843063
2015-01-06  5883.372070  1104.983765  1219.246460   984.705139     30.730652
2015-01-07  5847.976562  1089.056885  1205.058350   969.145020     30.716604